package org.codefilarete.stalactite.sql;

import org.codefilarete.stalactite.engine.SeparateTransactionExecutor;

/**
 * An abstraction for current JDBC connection configuration 
 * 
 * @author Guillaume Mary
 */
public interface ConnectionConfiguration {
	
	ConnectionProvider getConnectionProvider();
	
	int getBatchSize();
	
	/**
	 * Default implementation of {@link ConnectionConfiguration} that keeps and gives values provided at instantiation time
	 * 
	 * @author Guillaume Mary
	 */
	class ConnectionConfigurationSupport implements ConnectionConfiguration {
		
		private final ConnectionProvider connectionProvider;
		private final int batchSize;
		
		public ConnectionConfigurationSupport(ConnectionProvider connectionProvider, int batchSize) {
			this.connectionProvider = connectionProvider;
			this.batchSize = batchSize;
		}
		
		@Override
		public ConnectionProvider getConnectionProvider() {
			return connectionProvider;
		}
		
		@Override
		public int getBatchSize() {
			return batchSize;
		}
	}
	
	/**
	 * {@link ConnectionProvider} contract that fulfills {@link org.codefilarete.stalactite.engine.PersistenceContext} features 
	 * - entity versioning (pessimistic lock)
	 * - transactional operations (for identifiers generated by {@link org.codefilarete.stalactite.mapping.id.sequence.PooledHiLoSequence})
	 * 
	 * @author Guillaume Mary
	 */
	interface TransactionalConnectionProvider extends
			TransactionObserver, // for InsertExecutor.VersioningStrategyRollbackListener
			SeparateTransactionExecutor // for PooledHiLoSequence
	{
		
	}
	
}
