package org.codefilarete.stalactite.persistence.engine.runtime;

import org.codefilarete.stalactite.persistence.sql.H2Dialect;
import org.codefilarete.stalactite.sql.test.H2InMemoryDataSource;
import org.junit.jupiter.api.BeforeEach;

/**
 * Same as {@link InsertExecutorAutoGeneratedKeysITTest} but dedicated to H2 because of its implementation of generated keys.
 *
 * @author Guillaume Mary
 */
public class InsertExecutorAutoGeneratedKeysH2Test extends InsertExecutorAutoGeneratedKeysITTest {
	
	@Override
	@BeforeEach
	void createDialect() {
		dialect = new H2Dialect();
	}

	@Override
	@BeforeEach
	void createDataSource() {
		dataSource = new H2InMemoryDataSource();
	}
}