package org.codefilarete.stalactite.engine.runtime.load;

import javax.annotation.Nullable;
import java.util.ArrayDeque;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Queue;
import java.util.Random;
import java.util.Set;
import java.util.function.BiFunction;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.stream.Collectors;

import org.codefilarete.stalactite.engine.PolymorphismPolicy.SingleTablePolymorphism;
import org.codefilarete.stalactite.engine.runtime.EntityConfiguredJoinedTablesPersister;
import org.codefilarete.stalactite.engine.runtime.load.EntityInflater.EntityMappingAdapter;
import org.codefilarete.stalactite.engine.runtime.load.EntityMerger.EntityMergerAdapter;
import org.codefilarete.stalactite.engine.runtime.load.EntityTreeInflater.TreeInflationContext;
import org.codefilarete.stalactite.engine.runtime.load.MergeJoinNode.MergeJoinRowConsumer;
import org.codefilarete.stalactite.mapping.AbstractTransformer;
import org.codefilarete.stalactite.mapping.ColumnedRow;
import org.codefilarete.stalactite.mapping.RowTransformer;
import org.codefilarete.stalactite.mapping.RowTransformer.TransformerListener;
import org.codefilarete.stalactite.query.model.Query;
import org.codefilarete.stalactite.query.model.Selectable;
import org.codefilarete.stalactite.query.model.Selectable.SelectableString;
import org.codefilarete.stalactite.query.model.Union;
import org.codefilarete.stalactite.query.model.Union.PseudoColumn;
import org.codefilarete.stalactite.sql.ddl.structure.Column;
import org.codefilarete.stalactite.sql.ddl.structure.Table;
import org.codefilarete.stalactite.sql.result.BeanRelationFixer;
import org.codefilarete.stalactite.sql.result.Row;
import org.codefilarete.tool.Reflections;
import org.codefilarete.tool.VisibleForTesting;
import org.codefilarete.tool.bean.Randomizer;
import org.codefilarete.tool.bean.Randomizer.LinearRandomGenerator;
import org.codefilarete.tool.collection.Collections;
import org.codefilarete.tool.collection.Iterables;
import org.codefilarete.tool.collection.KeepOrderSet;
import org.codefilarete.tool.collection.ReadOnlyList;
import org.codefilarete.tool.function.Hanger.Holder;
import org.codefilarete.tool.trace.ModifiableInt;

import static org.codefilarete.stalactite.query.model.Operators.cast;

/**
 * Tree representing joins of a from clause, nodes are {@link JoinNode}.
 * It maintains an index of its joins based on an unique name for each, so they can be referenced outside {@link EntityJoinTree} without
 * depending on classes of this package (since the reference is a {@link String}).
 *
 * @author Guillaume Mary
 */
public class EntityJoinTree<C, I> {
	
	/**
	 * Key of the very first {@link EntityJoinTree} added to the join structure (the one generated by constructor), see {@link #getRoot()}
	 */
	public static final String ROOT_STRATEGY_NAME = "ROOT";
	
	private final JoinRoot<C, I, ?> root;
	
	/**
	 * A mapping between a name and a join to find them when we want to join one with another new one
	 * 
	 * @see #addRelationJoin(String, EntityInflater, Column, Column, String, JoinType, BeanRelationFixer, Set)
	 * @see #indexKeyGenerator
	 */
	private final Map<String, JoinNode> joinIndex = new HashMap<>();
	
	/**
	 * The objet that will help to give node names / keys into the index (no impact on the generated SQL)
	 * 
	 * @see #joinIndex
	 */
	private final NodeKeyGenerator indexKeyGenerator = new NodeKeyGenerator();
	
	private final Set<Table> tablesToBeExcludedFromDDL = Collections.newIdentitySet();
	
	public <T extends Table> EntityJoinTree(EntityInflater<C, I> rootEntityInflater, T table) {
		this.root = new JoinRoot<>(this, rootEntityInflater, table);
		this.joinIndex.put(ROOT_STRATEGY_NAME, root);
	}
	
	public JoinRoot<C, I, ?> getRoot() {
		return root;
	}
	
	/**
	 * Returns mapping between {@link JoinNode} and their internal name.
	 *
	 * @return an unmodifiable version of the internal mapping (because its maintenance responsability falls to current class)
	 */
	Map<String, JoinNode> getJoinIndex() {
		return java.util.Collections.unmodifiableMap(joinIndex);
	}
	
	/**
	 * Adds a join to this select.
	 * Use for one-to-one or one-to-many cases when join is used to describe a related bean.
	 *
	 * @param <U> type of bean mapped by the given strategy
	 * @param <T1> joined left table
	 * @param <T2> joined right table
	 * @param <ID> type of joined values
	 * @param leftStrategyName the name of a (previously) registered join. {@code leftJoinColumn} must be a {@link Column} of its left {@link Table}
	 * @param inflater the strategy of the mapped bean. Used to give {@link Column}s and {@link RowTransformer}
	 * @param leftJoinColumn the {@link Column} (of a previously registered join) to be joined with {@code rightJoinColumn}
	 * @param rightJoinColumn the {@link Column} to be joined with {@code leftJoinColumn}
	 * @param rightTableAlias optional alias for right table, if null table name will be used
	 * @param joinType says whether the join must be open
	 * @param beanRelationFixer a function to fulfill relation between beans
	 * @param additionalSelectableColumns columns to be added to SQL select clause out of ones took from given inflater, necessary for indexed relations
	 * @return the name of the created join, to be used as a key for other joins (through this method {@code leftStrategyName} argument)
	 */
	public <U, T1 extends Table<T1>, T2 extends Table<T2>, ID> String addRelationJoin(String leftStrategyName,
																					  EntityInflater<U, ID> inflater,
																					  Column<T1, ID> leftJoinColumn,
																					  Column<T2, ID> rightJoinColumn,
																					  String rightTableAlias,
																					  JoinType joinType,
																					  BeanRelationFixer<C, U> beanRelationFixer,
																					  Set<? extends Column<T2, ?>> additionalSelectableColumns) {
		return addRelationJoin(leftStrategyName, inflater, leftJoinColumn, rightJoinColumn, rightTableAlias, joinType, beanRelationFixer, additionalSelectableColumns, null);
	}
	
	/**
	 * Adds a join to this select.
	 * Use for one-to-one or one-to-many cases when join is used to describe a related bean.
	 * Difference with {@link #addRelationJoin(String, EntityInflater, Column, Column, String, JoinType, BeanRelationFixer, Set)} is last
	 * parameter : an optional function which computes an identifier of a relation between 2 entities, this is required to prevent from fulfilling
	 * twice the relation when SQL returns several times same identifier (when at least 2 collections are implied). By default this function is
	 * made of parentEntityId + childEntityId and can be overwritten here (in particular when relation is a List, entity index is added to computation).
	 * See {@link RelationJoinNode.RelationJoinRowConsumer#applyRelatedEntity(Object, Row, TreeInflationContext)} for usage.
	 *
	 * @param <U> type of bean mapped by the given strategy
	 * @param <T1> joined left table
	 * @param <T2> joined right table
	 * @param <ID> type of joined values
	 * @param leftStrategyName the name of a (previously) registered join. {@code leftJoinColumn} must be a {@link Column} of its left {@link Table}
	 * @param inflater the strategy of the mapped bean. Used to give {@link Column}s and {@link RowTransformer}
	 * @param leftJoinColumn the {@link Column} (of a previously registered join) to be joined with {@code rightJoinColumn}
	 * @param rightJoinColumn the {@link Column} to be joined with {@code leftJoinColumn}
	 * @param rightTableAlias optional alias for right table, if null table name will be used
	 * @param joinType says whether the join must be open
	 * @param beanRelationFixer a function to fulfill relation between beans
	 * @param additionalSelectableColumns columns to be added to SQL select clause out of ones took from given inflater, necessary for indexed relations
	 * @param relationIdentifierProvider relation identifier provider, not null for List cases : necessary because List may contain duplicate
	 * @return the name of the created join, to be used as a key for other joins (through this method {@code leftStrategyName} argument)
	 * @see RelationJoinNode.RelationJoinRowConsumer#applyRelatedEntity(Object, Row, TreeInflationContext)
	 */
	public <U, T1 extends Table<T1>, T2 extends Table<T2>, ID> String addRelationJoin(String leftStrategyName,
																					  EntityInflater<U, ID> inflater,
																					  Column<T1, ID> leftJoinColumn,
																					  Column<T2, ID> rightJoinColumn,
																					  @Nullable String rightTableAlias,
																					  JoinType joinType,
																					  BeanRelationFixer<C, U> beanRelationFixer,
																					  Set<? extends Column<T2, ?>> additionalSelectableColumns,
																					  @Nullable BiFunction<Row, ColumnedRow, ID> relationIdentifierProvider) {
		return this.<T1>addJoin(leftStrategyName, parent -> new RelationJoinNode<>(
				parent,
				leftJoinColumn, rightJoinColumn, joinType,
				new HashSet<>(Collections.cat(inflater.getSelectableColumns(), additionalSelectableColumns)),
				rightTableAlias,
				inflater,
				(BeanRelationFixer<Object, U>) beanRelationFixer,
				relationIdentifierProvider));
	}
	
	public <U, T1 extends Table, T2 extends Table, ID, JOINCOLTYPE> String addPolymorphicRelationJoin(
			String leftStrategyName,
			EntityConfiguredJoinedTablesPersister<U, ID> mainPersister,
			Column<T1, JOINCOLTYPE> leftJoinColumn,
			Column<T2, JOINCOLTYPE> rightJoinColumn,
			Set<EntityConfiguredJoinedTablesPersister<? extends U, ID>> subPersisters,
			BeanRelationFixer<C, U> beanRelationFixer,
			@Nullable BiFunction<Row, ColumnedRow, ID> relationIdentifierProvider) {
		
		Holder<PolymorphicRelationJoinNode<U, T1, T2, JOINCOLTYPE, ID>> createdJoinHolder = new Holder<>();
		String relationJoinName = this.<T1>addJoin(leftStrategyName, parent -> {
			PolymorphicRelationJoinNode<U, T1, T2, JOINCOLTYPE, ID> polymorphicRelationJoinNode = new PolymorphicRelationJoinNode<U, T1, T2, JOINCOLTYPE, ID>(
					parent,
					(Column) leftJoinColumn,
					(Column) rightJoinColumn,
					JoinType.OUTER,
					mainPersister.getMainTable().getColumns(),
					null,
					new EntityMappingAdapter<>(mainPersister.getMapping()),
					(BeanRelationFixer<Object, U>) beanRelationFixer,
					relationIdentifierProvider);
			createdJoinHolder.set(polymorphicRelationJoinNode);
			return polymorphicRelationJoinNode;
		});
		
		this.addPolymorphicSubPersistersJoins(relationJoinName, mainPersister, createdJoinHolder.get(), subPersisters);
		
		return relationJoinName;
	}
	
	private <U, V extends U, T1 extends Table, T2 extends Table, ID> void addPolymorphicSubPersistersJoins(String mainPolymorphicJoinNodeName,
																										   EntityConfiguredJoinedTablesPersister<U, ID> mainPersister,
																										   PolymorphicRelationJoinNode<U, T1, T2, ?, ID> mainPersisterJoin,
																										   Set<EntityConfiguredJoinedTablesPersister<? extends U, ID>> subPersisters) {
		subPersisters.forEach(subPersister -> {
			EntityConfiguredJoinedTablesPersister<V, ID> localSubPersister = (EntityConfiguredJoinedTablesPersister<V, ID>) subPersister;
			this.<T1>addJoin(mainPolymorphicJoinNodeName, parent -> new MergeJoinNode<V, T1, T2, ID>(parent,
					(Column) Iterables.first(mainPersister.getMainTable().getPrimaryKey().getColumns()),
					(Column) Iterables.first(subPersister.getMainTable().getPrimaryKey().getColumns()),
					JoinType.OUTER,
					null,
					new EntityMergerAdapter<>(localSubPersister.getMapping())) {
				@Override
				public MergeJoinRowConsumer<V> toConsumer(ColumnedRow columnedRow) {
					PolymorphicMergeJoinRowConsumer<U, V, ID> joinRowConsumer = new PolymorphicMergeJoinRowConsumer<>(
							new PolymorphicMergeEntityInflater<>(mainPersister, localSubPersister), columnedRow);
					mainPersisterJoin.addSubPersisterJoin(localSubPersister, joinRowConsumer);
					return joinRowConsumer;
				}
			});
		});
	}
	
	public <U, T1 extends Table, T2 extends Table, ID, JOINCOLTYPE> String addTablePerClassPolymorphicRelationJoin(
			String leftStrategyName,
			EntityConfiguredJoinedTablesPersister<U, ID> mainPersister,
			Column<T1, JOINCOLTYPE> leftJoinColumn,
			Column<T2, JOINCOLTYPE> rightJoinColumn,
			Set<EntityConfiguredJoinedTablesPersister<? extends U, ID>> subPersisters,
			BeanRelationFixer<C, U> beanRelationFixer) {
		
		
		// we build a union of all sub queries that will be joined in the main query
		// To build the union we need columns that are common to all persisters
		Set<Column<?, ?>> commonColumns = new KeepOrderSet<>();
		commonColumns.addAll(mainPersister.getMapping().getSelectableColumns());
		// TODO : right column is not in selected columns of class mapping : understand why (and if that's normal)
		commonColumns.add(rightJoinColumn);
		
		Set<String> commonColumnsNames = commonColumns.stream().map(Column::getName).collect(Collectors.toSet());
		
		KeepOrderSet<Column<?, ?>> nonCommonColumns = new KeepOrderSet<>();
		subPersisters.forEach(subPersister -> {
			nonCommonColumns.addAll(subPersister.getMainTable().getColumns());
		});
		nonCommonColumns.removeIf(c -> commonColumnsNames.contains(c.getName()));
		
		Union subPersistersUnion = new Union();
		String entityTypeDiscriminatorName = "clazz_";
		PseudoColumn<Integer> discriminatorPseudoColumn = subPersistersUnion.registerColumn(entityTypeDiscriminatorName, Integer.class);
		ModifiableInt discriminatorComputer = new ModifiableInt();
		
		subPersisters.forEach(subPersister -> {
			Query subEntityQuery = new Query(subPersister.getMapping().getTargetTable());
			subEntityQuery.select(String.valueOf(discriminatorComputer.increment()), Integer.class).as(entityTypeDiscriminatorName);
			subPersistersUnion.unionAll(subEntityQuery);
			
			commonColumns.forEach(column -> {
				subEntityQuery.select(column.getName(), column.getJavaType());
				subPersistersUnion.registerColumn(column.getName(), column.getJavaType());
			});
			
			nonCommonColumns.forEach(column -> {
				Selectable<?> expression;
				if (subPersister.getMapping().getSelectableColumns().contains(column)) {
					expression = new SelectableString<>(column.getName(), column.getJavaType());
				} else {
					expression = cast(null, column.getJavaType());
				}
				// we put an alias else cast(..) as no name which makes it doesn't match official-column name, and then
				// may cause an error since SQL in kind of invalid 
				subEntityQuery.select(expression, column.getName());
				subPersistersUnion.registerColumn(column.getName(), column.getJavaType());
			});
		});
		
		Holder<TablePerClassPolymorphicRelationJoinNode<U, T1, JOINCOLTYPE, ID>> createdJoinHolder = new Holder<>();
		String relationJoinName = this.<T1>addJoin(leftStrategyName, parent -> {
			TablePerClassPolymorphicRelationJoinNode<U, T1, JOINCOLTYPE, ID> relationJoinNode = new TablePerClassPolymorphicRelationJoinNode<>(parent,
					subPersistersUnion,
					leftJoinColumn,
					rightJoinColumn,
					JoinType.OUTER,
					subPersistersUnion.getColumns(),
					mainPersister.getClassToPersist().getSimpleName(),
					new EntityMappingAdapter<>(mainPersister.getMapping()),
					(BeanRelationFixer<Object, U>) beanRelationFixer,
					discriminatorPseudoColumn);
			createdJoinHolder.set(relationJoinNode);
			return relationJoinNode;
		});
		
		this.addTablePerClassPolymorphicSubPersistersJoins(relationJoinName, mainPersister, createdJoinHolder.get(), subPersisters);
		
		return relationJoinName;
	}
	
	private <U, V extends U, T1 extends Table, T2 extends Table, ID> void addTablePerClassPolymorphicSubPersistersJoins(String mainPolymorphicJoinNodeName,
																														EntityConfiguredJoinedTablesPersister<U, ID> mainPersister,
																														TablePerClassPolymorphicRelationJoinNode<U, T1, ?, ID> mainPersisterJoin,
																														Set<EntityConfiguredJoinedTablesPersister<? extends U, ID>> subPersisters) {
		
		ModifiableInt discriminatorComputer = new ModifiableInt();
		subPersisters.forEach(subPersister -> {
			EntityConfiguredJoinedTablesPersister<V, ID> localSubPersister = (EntityConfiguredJoinedTablesPersister<V, ID>) subPersister;
			this.<T1>addJoin(mainPolymorphicJoinNodeName, parent -> new MergeJoinNode<V, T1, T2, ID>(
					parent,
					(Column) Iterables.first(mainPersister.getMainTable().getPrimaryKey().getColumns()),
					(Column) Iterables.first(subPersister.getMainTable().getPrimaryKey().getColumns()),
					JoinType.OUTER,
					null,
					new EntityMergerAdapter<>(localSubPersister.getMapping())) {
				@Override
				public MergeJoinRowConsumer<V> toConsumer(ColumnedRow columnedRow) {
					PolymorphicMergeJoinRowConsumer<U, V, ID> joinRowConsumer = new PolymorphicMergeJoinRowConsumer<>(
							new PolymorphicMergeEntityInflater<>(mainPersister, localSubPersister), columnedRow);
					mainPersisterJoin.addSubPersisterJoin(localSubPersister, joinRowConsumer, discriminatorComputer.increment());
					return joinRowConsumer;
				}
			});
		});
	}
	
	public <U, T1 extends Table, T2 extends Table, ID, JOINCOLTYPE, DTYPE> String addSingleTablePolymorphicRelationJoin(
			String leftStrategyName,
			EntityConfiguredJoinedTablesPersister<U, ID> mainPersister,
			Column<T1, JOINCOLTYPE> leftJoinColumn,
			Column<T2, JOINCOLTYPE> rightJoinColumn,
			Set<EntityConfiguredJoinedTablesPersister<? extends U, ID>> subPersisters,
			BeanRelationFixer<C, U> beanRelationFixer,
			SingleTablePolymorphism<U, DTYPE> polymorphismPolicy,
			Column<T2, DTYPE> discriminatorColumn) {
		
		Holder<SingleTablePolymorphicRelationJoinNode<U, T1, T2, JOINCOLTYPE, ID, DTYPE>> createdJoinHolder = new Holder<>();
		String relationJoinName = this.<T1>addJoin(leftStrategyName, parent -> {
			SingleTablePolymorphicRelationJoinNode<U, T1, T2, JOINCOLTYPE, ID, DTYPE> polymorphicRelationJoinNode = new SingleTablePolymorphicRelationJoinNode<U, T1, T2, JOINCOLTYPE, ID, DTYPE>(
					parent,
					(Column) leftJoinColumn,
					(Column) rightJoinColumn,
					JoinType.OUTER,
					mainPersister.getMainTable().getColumns(),
					null,
					new EntityMappingAdapter<>(mainPersister.getMapping()),
					(BeanRelationFixer<Object, U>) beanRelationFixer,
					discriminatorColumn) {

				@Override
				public SingleTablePolymorphicRelationJoinNode<U, T1, T2, JOINCOLTYPE, ID, DTYPE>.SingleTablePolymorphicRelationJoinRowConsumer toConsumer(ColumnedRow columnedRow) {
					SingleTablePolymorphicRelationJoinNode<U, T1, T2, JOINCOLTYPE, ID, DTYPE>.SingleTablePolymorphicRelationJoinRowConsumer joinTablePolymorphicRelationJoinRowConsumer = super.toConsumer(columnedRow);
					addSingleTableSubPersistersJoin(mainPersister, this, subPersisters, columnedRow, polymorphismPolicy);
					return joinTablePolymorphicRelationJoinRowConsumer;
				}
			};
			createdJoinHolder.set(polymorphicRelationJoinNode);
			return polymorphicRelationJoinNode;
		});
		
		return relationJoinName;
	}
	
	private <U, V extends U, T1 extends Table, T2 extends Table, JOINCOLTYPE, ID, DTYPE> void addSingleTableSubPersistersJoin(
			EntityConfiguredJoinedTablesPersister<U, ID> mainPersister,
			SingleTablePolymorphicRelationJoinNode<U, T1, T2, JOINCOLTYPE, ID, DTYPE> mainPersisterJoin,
			Set<EntityConfiguredJoinedTablesPersister<? extends U, ID>> subPersisters,
			ColumnedRow columnedRow,
			SingleTablePolymorphism<U, DTYPE> polymorphismPolicy) {
		
		subPersisters.forEach(subPersister -> {
			EntityConfiguredJoinedTablesPersister<V, ID> localSubPersister = (EntityConfiguredJoinedTablesPersister<V, ID>) subPersister;
			PolymorphicMergeJoinRowConsumer<U, V, ID> joinRowConsumer = new PolymorphicMergeJoinRowConsumer<U, V, ID>(
					new PolymorphicMergeEntityInflater<>(mainPersister, localSubPersister), columnedRow);
			mainPersisterJoin.addSubPersisterJoin(localSubPersister, joinRowConsumer, polymorphismPolicy.getDiscriminatorValue(localSubPersister.getClassToPersist()));
		});
	}



	static class PolymorphicMergeEntityInflater<E, D extends E, I, T extends Table<T>> implements EntityInflater<D, I> {
		
		private final EntityConfiguredJoinedTablesPersister<E, I> mainPersister;
		
		private final EntityConfiguredJoinedTablesPersister<D, I> subPersister;
		
		PolymorphicMergeEntityInflater(EntityConfiguredJoinedTablesPersister<E, I> mainPersister,
									   EntityConfiguredJoinedTablesPersister<D, I> subPersister) {
			this.mainPersister = mainPersister;
			this.subPersister = subPersister;
		}
		
		@Override
		public Class<D> getEntityType() {
			return subPersister.getClassToPersist();
		}
		
		@Override
		public I giveIdentifier(Row row, ColumnedRow columnedRow) {
			return mainPersister.getMapping().getIdMapping().getIdentifierAssembler().assemble(row, columnedRow);
		}
		
		@Override
		public RowTransformer<D> copyTransformerWithAliases(ColumnedRow columnedRow) {
			return subPersister.getMapping().copyTransformerWithAliases(columnedRow);
		}
		
		@Override
		public Set<Selectable<?>> getSelectableColumns() {
			return (Set) subPersister.getMapping().getSelectableColumns();
		}
	}
	
	static class PolymorphicMergeJoinRowConsumer<C, D extends C, I> extends MergeJoinRowConsumer<D> {
		
		private final BiFunction<Row, ColumnedRow, I> identifierProvider;
		
		private final ColumnedRow columnedRow;
		
		public PolymorphicMergeJoinRowConsumer(PolymorphicMergeEntityInflater<C, D, I, ?> entityInflater,
											   ColumnedRow columnedRow) {
			super(entityInflater.copyTransformerWithAliases(columnedRow));
			this.identifierProvider = entityInflater::giveIdentifier;
			this.columnedRow = columnedRow;
		}
		
		@Nullable
		public I giveIdentifier(Row row) {
			return identifierProvider.apply(row, columnedRow);
		}
		
		public D transform(Row row) {
			return super.merger.transform(row);
		}
	}
	
	/**
	 * Adds a join to this select.
	 * Use for inheritance cases when joined data are used to complete an existing bean.
	 *
	 * @param <U> type of bean mapped by the given strategy
	 * @param <T1> left table type
	 * @param <T2> right table type
	 * @param <ID> type of joined values
	 * @param leftStrategyName the name of a (previously) registered join. {@code leftJoinColumn} must be a {@link Column} of its left {@link Table}.
	 * 						Right table data will be merged with this "root".
	 * @param inflater the strategy of the mapped bean. Used to give {@link Column}s and {@link RowTransformer}
	 * @param leftJoinColumn the {@link Column} (of previous strategy left table) to be joined with {@code rightJoinColumn}
	 * @param rightJoinColumn the {@link Column} (of the strategy table) to be joined with {@code leftJoinColumn}
	 * @return the name of the created join, to be used as a key for other joins (through this method {@code leftStrategyName} argument)
	 */
	public <U, T1 extends Table<T1>, T2 extends Table<T2>, ID> String addMergeJoin(String leftStrategyName,
																				   EntityMerger<U, T2> inflater,
																				   Column<T1, ID> leftJoinColumn,
																				   Column<T2, ID> rightJoinColumn) {
		return this.<T1>addJoin(leftStrategyName, parent -> new MergeJoinNode<>(parent,
				leftJoinColumn, rightJoinColumn, JoinType.INNER,
				null, inflater));
	}
	
	/**
	 * Adds a merge join to this select : no bean will be created by given {@link EntityInflater}, only its
	 * {@link AbstractTransformer#applyRowToBean(Row, Object)} will be used during bean graph loading process.
	 *
	 * @param <T1> left table type
	 * @param <T2> right table type
	 * @param <ID> type of joined values
	 * @param leftStrategyName join name on which join must be created
	 * @param entityMerger strategy to be used to load bean
	 * @param leftJoinColumn left join column, expected to be one of left strategy table
	 * @param rightJoinColumn right join column
	 * @param joinType type of join to create
	 * @return the name of the created join, to be used as a key for other joins (through this method {@code leftStrategyName} argument)
	 */
	public <U, T1 extends Table<T1>, T2 extends Table<T2>, ID> String addMergeJoin(String leftStrategyName,
																				   EntityMerger<U, T2> entityMerger,
																				   Column<T1, ID> leftJoinColumn,
																				   Column<T2, ID> rightJoinColumn,
																				   JoinType joinType) {
		return this.<T1>addJoin(leftStrategyName, parent -> new MergeJoinNode<>(parent,
				leftJoinColumn, rightJoinColumn, joinType,
				null, entityMerger));
	}
	
	/**
	 * Adds a passive join to this select : this kind of join doesn't take part to bean construction, it aims only at adding an SQL join to
	 * bean graph loading.
	 *
	 * @param leftStrategyName join name on which join must be created
	 * @param leftJoinColumn left join column, expected to be one of left strategy table
	 * @param rightJoinColumn right join column
	 * @param joinType type of join to create
	 * @param columnsToSelect columns that must be added to final select
	 * @param <T1> left table type
	 * @param <T2> right table type
	 * @param <ID> type of joined values
	 * @return the name of the created join, to be used as a key for other joins (through this method {@code leftStrategyName} argument)
	 */
	public <T1 extends Table<T1>, T2 extends Table<T2>, ID> String addPassiveJoin(String leftStrategyName,
																				  Column<T1, ID> leftJoinColumn,
																				  Column<T2, ID> rightJoinColumn,
																				  JoinType joinType,
																				  Set<Column<T2, ?>> columnsToSelect) {
		return this.<T1>addJoin(leftStrategyName, parent -> new PassiveJoinNode<>(parent,
				leftJoinColumn, rightJoinColumn, joinType,
				columnsToSelect, null));
	}
	
	public <T1 extends Table<T1>, T2 extends Table<T2>, ID> String addPassiveJoin(String leftStrategyName,
																				  Column<T1, ID> leftJoinColumn,
																				  Column<T2, ID> rightJoinColumn,
																				  JoinType joinType,
																				  Set<Column<T2, ?>> columnsToSelect,
																				  TransformerListener<C> transformerListener) {
		return this.<T1>addJoin(leftStrategyName, parent -> new PassiveJoinNode<>(parent,
				leftJoinColumn, rightJoinColumn, joinType,
				columnsToSelect, null).setTransformerListener((TransformerListener<Object>) transformerListener));
	}
	
	public <T1 extends Table<T1>, T2 extends Table<T2>, ID> String addPassiveJoin(String leftStrategyName,
																				  Column<T1, ID> leftJoinColumn,
																				  Column<T2, ID> rightJoinColumn,
																				  String tableAlias,
																				  JoinType joinType,
																				  Set<Column<T2, ?>> columnsToSelect,
																				  TransformerListener<C> transformerListener,
																				  boolean rightTableParticipatesToDDL) {
		if (rightTableParticipatesToDDL) {
			tablesToBeExcludedFromDDL.add(rightJoinColumn.getTable());
		}
		return this.<T1>addJoin(leftStrategyName, parent -> new PassiveJoinNode<>(parent,
				leftJoinColumn, rightJoinColumn, joinType,
				columnsToSelect, tableAlias).setTransformerListener((TransformerListener<Object>) transformerListener));
	}
	
	private <T extends Table> String addJoin(String leftStrategyName, Function<JoinNode<T> /* parent node */, AbstractJoinNode> joinNodeSupplier) {
		JoinNode<T> owningJoin = getJoin(leftStrategyName);
		if (owningJoin == null) {
			throw new IllegalArgumentException("No strategy with name " + leftStrategyName + " exists to add a new strategy on");
		}
		AbstractJoinNode joinNode = joinNodeSupplier.apply(owningJoin);
		String joinName = this.indexKeyGenerator.generateKey(joinNode);
		this.joinIndex.put(joinName, joinNode);
		return joinName;
	}
	
	/**
	 * Gives a particular node of the joins graph by its name. Joins graph name are given in return of
	 * {@link #addRelationJoin(String, EntityInflater, Column, Column, String, JoinType, BeanRelationFixer, Set)}.
	 * When {@link #ROOT_STRATEGY_NAME} is given, {@link #getRoot()} will be used, meanwhile, be aware that using this method to retreive root node
	 * is not the recommended way : prefer usage of {@link #getRoot()} to prevent exposure of {@link #ROOT_STRATEGY_NAME}
	 *
	 * @param leftStrategyName join node name to be given
	 * @return null if the node doesn't exist
	 * @see #getRoot()
	 */
	@Nullable
	public <T extends Table> JoinNode<T> getJoin(String leftStrategyName) {
		return (JoinNode<T>) this.joinIndex.get(leftStrategyName);
	}
	
	/**
	 * Returns node that joins given columns. Comparison between columns and node ones is made using reference checking, not equality, because
	 * there's no limitation on multiple presence of same join in the tree, overall with identical column name, so to enforce finding the matching
	 * join we use reference check.
	 * Mainly done for testing purpose.
	 * 
	 * @param leftColumn a column to be compared to left columns of this tree
	 * @param rightColumn a column to be compared to right columns of this tree
	 * @return the join that as same left and right column as given ones, null if none exists
	 */
	@VisibleForTesting
	<T1 extends Table, T2 extends Table, E, ID, O> AbstractJoinNode<E, T1, T2, ID> giveJoin(Column<T1, O> leftColumn, Column<T2, O> rightColumn) {
		return Iterables.find(joinIterator(), node -> node.getLeftJoinColumn() == leftColumn && node.getRightJoinColumn() == rightColumn);
	}
	
	/**
	 * Gives all tables used by this tree
	 *
	 * @return all joins tables of this tree
	 */
	public Set<Table> giveTables() {
		// because Table implements an hashCode on their name, we can use an HashSet to avoid duplicates
		Set<Table> result = new HashSet<>();
		result.add(root.getTable());
		foreachJoin(node -> {
			if (node.getTable() instanceof Table && !tablesToBeExcludedFromDDL.contains(node.getTable())) {
				result.add((Table) node.getTable());
			}
		});
		return result;
	}
	
	/**
	 * Shortcut for {@code joinIterator().forEachRemaining()}.
	 * Goes down this tree by breadth first. Made to avoid everyone implements node iteration.
	 * Consumer is invoked foreach node <strong>except root</strong> because it usually has a special treatment.
	 * Traversal is made in pre-order : node is consumed first then its children.
	 * 
	 * @param consumer a {@link AbstractJoinNode} consumer
	 */
	public void foreachJoin(Consumer<AbstractJoinNode> consumer) {
		joinIterator().forEachRemaining(consumer);
	}
	
	/**
	 * Copies this tree onto given one under given join node name
	 * 
	 * @param target tree receiving copies of this tree nodes
	 * @param joinNodeName node name under which this tree must be copied, 
	 * @param <E> main entity type of target tree
	 * @param <ID> main entity identifier type of target tree
	 */
	public <E, ID> void projectTo(EntityJoinTree<E, ID> target, String joinNodeName) {
		projectTo(target.getJoin(joinNodeName));
	}
	
	public void projectTo(JoinNode<Table> joinNode) {
		EntityJoinTree<?, ?> tree = joinNode.getTree();
		foreachJoinWithDepth(joinNode, (targetOwner, currentNode) -> {
			// cloning each node, the only difference lays on left column : target gets its matching column 
			Column projectedLeftColumn = ((Table) targetOwner.getTable()).getColumn(currentNode.getLeftJoinColumn().getExpression());
			if (projectedLeftColumn == null) {
				throw new IllegalArgumentException("Expected column "
						+ currentNode.getLeftJoinColumn().getExpression() + " to exist in target table " + targetOwner.getTable().getName());
			}
			AbstractJoinNode nodeClone = copyNodeToParent(currentNode, targetOwner, projectedLeftColumn);
			// maintaining join names through trees : we add current node name to target one. Then nodes can be found across trees
			Set<Map.Entry<String, JoinNode>> set = this.joinIndex.entrySet();
			Entry<String, JoinNode> nodeName = Iterables.find(set, entry -> entry.getValue() == currentNode);
			tree.joinIndex.put(nodeName.getKey(), nodeClone);
			
			return nodeClone;
		});
	}
	
	/**
	 * Creates an {@link Iterator} that goes down this tree by breadth first. Made to avoid everyone implements node iteration.
	 * Consumer is invoked foreach node <strong>except root</strong> because it usually has a special treatment.
	 * Traversal is made in pre-order : node is consumed first then its children.
	 */
	public Iterator<AbstractJoinNode> joinIterator() {
		return new NodeIterator();
	}
	
	/**
	 * Goes down this tree by breadth first.
	 * Consumer is invoked foreach node <strong>except root</strong> because it usually has a special treatment.
	 * Used to create an equivalent tree of this instance with another type of node. This generally requires knowing current parent to allow child
	 * addition : consumer gets current parent as a first argument
	 * 
	 * @param initialNode very first parent given as first argument to consumer
	 * @param consumer producer of target tree node, gets node of this tree and parent node of target tree to add created node to it
	 * @param <S> type of node of the equivalent tree
	 */
	<S> void foreachJoinWithDepth(S initialNode, BiFunction<S, AbstractJoinNode, S> consumer) {
		Queue<S> targetPath = new ArrayDeque<>();
		targetPath.add(initialNode);
		NodeIteratorWithDepth<S> nodeIterator = new NodeIteratorWithDepth<>(targetPath, consumer);
		// We simply iterate all over the iterator to consume all elements
		// Please note that forEachRemaining can't be used because it is unsupported by NodeIteratorWithDepth 
		while (nodeIterator.hasNext()) {
			nodeIterator.next();
		}
		
	}
	
	/**
	 * Internal class that focuses on nodes. Iteration node is made breadth-first.
	 */
	private class NodeIterator implements Iterator<AbstractJoinNode> {
		
		protected final Queue<AbstractJoinNode> joinStack;
		protected AbstractJoinNode currentNode;
		protected boolean nextDepth = false;
		
		public NodeIterator() {
			joinStack = new ArrayDeque<>(root.getJoins());
		}
		
		@Override
		public boolean hasNext() {
			return !joinStack.isEmpty();
		}
		
		@Override
		@SuppressWarnings("java:S2272")    // NoSuchElementException is manged by Queue#remove()
		public AbstractJoinNode next() {
			// we prefer remove() to poll() because it manages NoSuchElementException which is also in next() contract
			currentNode = joinStack.remove();
			ReadOnlyList<AbstractJoinNode> nextJoins = currentNode.getJoins();
			joinStack.addAll(nextJoins);
			nextDepth = !nextJoins.isEmpty();
			return currentNode;
		}
	}
	
	private class NodeIteratorWithDepth<S> extends NodeIterator {
		
		private final Queue<S> targetPath;
		private final BiFunction<S, AbstractJoinNode, S> consumer;
		
		public NodeIteratorWithDepth(Queue<S> targetPath, BiFunction<S, AbstractJoinNode, S> consumer) {
			this.targetPath = targetPath;
			this.consumer = consumer;
		}
		
		@Override
		public AbstractJoinNode next() {
			super.next();
			S targetOwner = targetPath.peek();
			S nodeClone = consumer.apply(targetOwner, currentNode);
			if (nextDepth) {
				targetPath.add(nodeClone);
			}
			
			// if depth changes, we must remove target depth
			AbstractJoinNode nextIterationNode = joinStack.peek();
			if (nextIterationNode != null && nextIterationNode.getParent() != currentNode.getParent()) {
				targetPath.remove();
			}
			
			return currentNode;
		}
		
		@Override
		public void forEachRemaining(Consumer<? super AbstractJoinNode> action) {
			// this is not supported since a consumer is already given to constructor
			throw new UnsupportedOperationException();
		}
	}
	
	/**
	 * Copies given node and set it as a child of given parent.
	 * Could have been implemented by each node class itself but since this behavior is required only by the tree and a particular algorithm, decision
	 * mas made to do it outside them.
	 * 
	 * @param node node to be cloned
	 * @param parent parent node target of the clone
	 * @param leftColumn column to be used as the left one of the new node
	 * @return a copy of given node, put as child of parent, using leftColumn
	 */
	public static AbstractJoinNode copyNodeToParent(AbstractJoinNode node, JoinNode parent, Column leftColumn) {
		AbstractJoinNode nodeCopy;
		if (node instanceof RelationJoinNode) {
			nodeCopy = new RelationJoinNode(
					parent,
					leftColumn,
					node.getRightJoinColumn(),
					node.getJoinType(),
					node.getColumnsToSelect(),
					node.getTableAlias(),
					((RelationJoinNode) node).getEntityInflater(),
					((RelationJoinNode) node).getBeanRelationFixer(),
					((RelationJoinNode) node).getRelationIdentifierProvider());
		} else if (node instanceof MergeJoinNode) {
			nodeCopy = new MergeJoinNode(
					parent,
					leftColumn,
					node.getRightJoinColumn(),
					node.getJoinType(),
					node.getTableAlias(),
					((MergeJoinNode) node).getMerger());
		} else if (node instanceof PassiveJoinNode) {
			nodeCopy = new PassiveJoinNode(
					parent,
					leftColumn,
					node.getRightJoinColumn(),
					node.getJoinType(),
					node.getColumnsToSelect(),
					node.getTableAlias());
		} else {
			throw new UnsupportedOperationException("Unexpected type of join : some algorithm has changed, please implement it here or fix it : "
					+ Reflections.toString(node.getClass()));
		}
		nodeCopy.setTransformerListener(node.getTransformerListener());
		
		return nodeCopy;
	}
	
	private class NodeKeyGenerator {
		
		/**
		 * We don't use {@link java.security.SecureRandom} because it consumes too much time while computing random values (more than 500ms
		 * for a 6-digit identifier ! ... for each Node !!), and there's no need for security here.
		 */
		private final Randomizer keyGenerator = new Randomizer(new LinearRandomGenerator(new Random()));
		
		private String generateKey(JoinNode node) {
			// We generate a name which is unique across trees so node clones can be found outside this class by their name on different trees.
			// This is necessary for particular case of reading indexing column of indexed collection with an association table : the node that needs
			// to use indexing column is not the owner of the association table clone hence it can't use it (see table clone mechanism at EntityTreeQueryBuilder).
			// Said differently the "needer" is the official owner whereas the indexing column is on another node dedicated to the relation table maintenance.
			// The found way for the official node to access data through the indexing column is to use the identifier of the relation table node,
			// because it has it when it is created (see OneToManyWithIndexedAssociationTableEngine), and because the node is cloned through tree
			// the identifier should be "universal".
			// Note that this naming strategy could be more chaotic (totally random) since names are only here to give a unique identifier to joins
			// but the hereafter algorithm can help for debug
			return node.getTable().getAbsoluteName()
					+ "-" + Integer.toHexString(System.identityHashCode(EntityJoinTree.this)) + "-" + keyGenerator.randomHexString(6);
		}
	}
	
	public enum JoinType {
		INNER,
		OUTER
	}
	
}
