package org.codefilarete.stalactite.persistence.sql;

import java.util.Collections;

import org.codefilarete.stalactite.persistence.sql.ddl.DDLTableGenerator;
import org.codefilarete.stalactite.persistence.sql.ddl.SqlTypeRegistry;
import org.codefilarete.stalactite.persistence.structure.Column;
import org.codefilarete.stalactite.query.builder.DMLNameProvider;
import org.codefilarete.stalactite.sql.statement.binder.PostgreSQLTypeMapping;

/**
 * @author Guillaume Mary
 */
public class PostgreSQLDialect extends Dialect {
	
	public PostgreSQLDialect() {
		super(new PostgreSQLTypeMapping());
	}

	@Override
	public DDLTableGenerator newDdlTableGenerator() {
		return new PostgreSQLDDLTableGenerator(getSqlTypeRegistry());
	}

	public static class PostgreSQLDDLTableGenerator extends DDLTableGenerator {

		public PostgreSQLDDLTableGenerator(SqlTypeRegistry typeMapping) {
			super(typeMapping, new DMLNameProvider(Collections.emptyMap()));
		}

		@Override
		protected String getSqlType(Column column) {
			String sqlType;
			if (column.isAutoGenerated()) {
				sqlType = " SERIAL";
			} else {
				sqlType = super.getSqlType(column);
			}
			return sqlType;
		}
	}
	
}
