package org.gama.stalactite.persistence.engine.runtime;

import org.gama.stalactite.persistence.sql.DerbyDialect;
import org.gama.stalactite.sql.test.DerbyInMemoryDataSource;
import org.junit.jupiter.api.BeforeEach;

/**
 * Same as {@link InsertExecutorAutoGeneratedKeysITTest} but dedicated to Derby because of its implementation of generated keys.
 *
 * @author Guillaume Mary
 */
public class InsertExecutorAutoGeneratedKeysDerbyTest extends InsertExecutorAutoGeneratedKeysITTest {
	
	@Override
	@BeforeEach
	void createDialect() {
		dialect = new DerbyDialect();
	}

	@Override
	@BeforeEach
	void createDataSource() {
		dataSource = new DerbyInMemoryDataSource();
	}
}