package org.gama.stalactite.persistence.sql;

import javax.annotation.Nonnull;
import java.util.Collections;
import java.util.Map;
import java.util.Set;

import org.gama.lang.collection.Arrays;
import org.gama.stalactite.persistence.sql.ddl.DDLAppender;
import org.gama.stalactite.persistence.sql.ddl.DDLTableGenerator;
import org.gama.stalactite.persistence.sql.ddl.SqlTypeRegistry;
import org.gama.stalactite.persistence.structure.Column;
import org.gama.stalactite.persistence.structure.PrimaryKey;
import org.gama.stalactite.persistence.structure.Table;
import org.gama.stalactite.query.builder.DMLNameProvider;
import org.gama.stalactite.sql.binder.HSQLDBTypeMapping;

/**
 * @author Guillaume Mary
 */
public class HSQLDBDialect extends Dialect { 
	
	public HSQLDBDialect() {
		super(new HSQLDBTypeMapping());
	}
	
	@Override
	protected HSQLDBDDLTableGenerator newDdlTableGenerator() {
		return new HSQLDBDDLTableGenerator(getSqlTypeRegistry());
	}
	
	public static class HSQLDBDDLTableGenerator extends DDLTableGenerator {
		
		public HSQLDBDDLTableGenerator(SqlTypeRegistry typeMapping) {
			super(typeMapping, new HSQLDBDMLNameProvier(Collections.emptyMap()));
		}
		
		@Override
		protected String getSqlType(Column column) {
			String sqlType = super.getSqlType(column);
			if (column.isAutoGenerated()) {
				sqlType += " GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1)";
			}
			return sqlType;
		}
		
		/** Overriden to implement HSQLDB "unique" keyword */
		@Override
		protected void generateCreatePrimaryKey(PrimaryKey primaryKey, DDLAppender sqlCreateTable) {
			sqlCreateTable.cat(", unique (")
					.ccat(primaryKey.getColumns(), ", ")
					.cat(")");
		}
	}
	
	
	public static class HSQLDBDMLNameProvier extends DMLNameProvider {
		
		/** HSQLDB keywords to be escape. TODO: to be completed */
		public static final Set<String> KEYWORDS = Collections.unmodifiableSet(Arrays.asTreeSet(String.CASE_INSENSITIVE_ORDER));
		
		public HSQLDBDMLNameProvier(Map<Table, String> tableAliases) {
			super(tableAliases);
		}
		
		@Override
		public String getSimpleName(@Nonnull Column column) {
			if (KEYWORDS.contains(column.getName())) {
				return "`" + column.getName() + "`";
			}
			return super.getSimpleName(column);
		}
		
		@Override
		public String getSimpleName(Table table) {
			if (KEYWORDS.contains(table.getName())) {
				return "`" + super.getSimpleName(table) + "`";
			}
			return super.getSimpleName(table);
		}
	}
	
}
