package org.gama.stalactite.persistence.engine.runtime;

import javax.sql.DataSource;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import org.gama.lang.collection.Arrays;
import org.gama.lang.collection.Iterables;
import org.gama.lang.exception.Exceptions;
import org.gama.reflection.Accessors;
import org.gama.reflection.PropertyAccessor;
import org.gama.stalactite.persistence.engine.DDLDeployer;
import org.gama.stalactite.persistence.engine.runtime.AbstractDMLExecutorTest.Toto;
import org.gama.stalactite.persistence.id.manager.IdentifierInsertionManager;
import org.gama.stalactite.persistence.id.manager.JDBCGeneratedKeysIdentifierManager;
import org.gama.stalactite.persistence.mapping.ClassMappingStrategy;
import org.gama.stalactite.persistence.mapping.PersistentFieldHarverster;
import org.gama.stalactite.persistence.mapping.SinglePropertyIdAccessor;
import org.gama.stalactite.persistence.sql.ConnectionConfiguration.ConnectionConfigurationSupport;
import org.gama.stalactite.persistence.sql.Dialect;
import org.gama.stalactite.persistence.sql.dml.WriteOperationFactory;
import org.gama.stalactite.persistence.structure.Column;
import org.gama.stalactite.persistence.structure.Table;
import org.gama.stalactite.sql.ConnectionProvider;
import org.gama.stalactite.sql.DataSourceConnectionProvider;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * @author Guillaume Mary
 */
abstract class InsertExecutorAutoGeneratedKeysITTest {

	protected DataSource dataSource;
	
	protected Dialect dialect;

	@BeforeEach
	abstract void createDialect();
	
	@BeforeEach
	abstract void createDataSource();
	
	protected ClassMappingStrategy<Toto, Integer, Table> buildAutoGeneratedKeysPersistenceConfiguration() {
		Table targetTable = new Table("Toto");
		PersistentFieldHarverster persistentFieldHarverster = new PersistentFieldHarverster();
		Map<PropertyAccessor<Toto, Object>, Column<Table, Object>> mappedFileds = persistentFieldHarverster.mapFields(Toto.class, targetTable);
		PropertyAccessor<Toto, Integer> primaryKeyAccessor = Accessors.propertyAccessor(persistentFieldHarverster.getField("a"));
		Column primaryKeyColumn = persistentFieldHarverster.getColumn(primaryKeyAccessor);
		primaryKeyColumn.primaryKey();
		primaryKeyColumn.setAutoGenerated(true);

		// changing mapping strategy to add JDBCGeneratedKeysIdentifierManager and GeneratedKeysReader
		IdentifierInsertionManager<Toto, Integer> identifierGenerator = new JDBCGeneratedKeysIdentifierManager<>(
			new SinglePropertyIdAccessor<>(primaryKeyAccessor),
			dialect.buildGeneratedKeysReader(primaryKeyColumn.getName(), primaryKeyColumn.getJavaType()),
			Integer.class);
		
		ConnectionProvider connectionProvider = new DataSourceConnectionProvider(dataSource);
		DDLDeployer ddlDeployer = new DDLDeployer(dialect.getSqlTypeRegistry(), connectionProvider);
		
		ddlDeployer.getDdlGenerator().setDdlTableGenerator(dialect.getDdlTableGenerator());
		ddlDeployer.getDdlGenerator().setTables(Arrays.asSet(targetTable));
		ddlDeployer.deployDDL();
		try {
			connectionProvider.giveConnection().commit();
		} catch (SQLException e) {
			throw Exceptions.asRuntimeException(e);
		}
		
		return new ClassMappingStrategy<>(
			Toto.class,
			targetTable,
			mappedFileds,
			primaryKeyAccessor,
			identifierGenerator);
	}
	
	@Test
	void insert_generated_pk_real_life() {
		ClassMappingStrategy<Toto, Integer, Table> persistenceConfiguration = buildAutoGeneratedKeysPersistenceConfiguration();
		
		ConnectionProvider connectionProvider = new DataSourceConnectionProvider(dataSource);
		
		InsertExecutor<Toto, Integer, Table> testInstance = new InsertExecutor<>(persistenceConfiguration,
				new ConnectionConfigurationSupport(connectionProvider, 3), dialect.getDmlGenerator(), new WriteOperationFactory(), 3);
		List<Toto> totoList = Arrays.asList(new Toto(17, 23), new Toto(29, 31), new Toto(37, 41), new Toto(43, 53));
		testInstance.insert(totoList);
		
		// Verfy that database generated keys were set to Java instances
		assertThat(Iterables.collectToList(totoList, toto -> toto.a)).isEqualTo(Arrays.asList(1, 2, 3, 4));
	}
}