package org.codefilarete.stalactite.sql.ddl;


import org.codefilarete.stalactite.sql.ddl.structure.Column;

/**
 * @author Guillaume Mary
 */
public class DerbyDDLTableGenerator extends DDLTableGenerator {
	
	public DerbyDDLTableGenerator(SqlTypeRegistry typeMapping) {
		super(typeMapping);
	}
	
	/**
	 * Overridden to take identity column into account : Derby script must be adapted
	 */
	@Override
	protected String getSqlType(Column column) {
		String sqlType = super.getSqlType(column);
		if (column.isAutoGenerated()) {
			sqlType += " GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1)";
		}
		return sqlType;
	}
}
