package org.gama.stalactite.persistence.sql;

import java.util.Collections;

import org.gama.lang.StringAppender;
import org.gama.stalactite.persistence.sql.ddl.DDLTableGenerator;
import org.gama.stalactite.persistence.sql.ddl.SqlTypeRegistry;
import org.gama.stalactite.persistence.structure.Column;
import org.gama.stalactite.persistence.structure.ForeignKey;
import org.gama.stalactite.persistence.structure.Index;

/**
 * @author Guillaume Mary
 */
public class MariaDBDDLTableGenerator extends DDLTableGenerator {
	
	public MariaDBDDLTableGenerator(SqlTypeRegistry typeMapping) {
		super(typeMapping, new MariaDBDMLNameProvier(Collections.emptyMap()));
	}
	
	/**
	 * Overriden to change "drop constraint" into "drop foreign key", MariaDB specific
	 */
	@Override
	public String generateDropForeignKey(ForeignKey foreignKey) {
		StringAppender sqlCreateTable = new StringAppender("alter table ", dmlNameProvider.getSimpleName(foreignKey.getTable()),
			" drop foreign key ", foreignKey.getName());
		return sqlCreateTable.toString();
	}
	
	@Override
	public String generateDropIndex(Index index) {
		StringAppender sqlDropColumn = new StringAppender("alter table ", dmlNameProvider.getSimpleName(index.getTable()),
			" drop index ", index.getName());
		return sqlDropColumn.toString();
	}
	
	@Override
	protected String getSqlType(Column column) {
		String sqlType = super.getSqlType(column);
		if (column.isAutoGenerated()) {
			sqlType += " auto_increment";
		}
		return sqlType;
	}
}
